databases:
  - name: Orimeguri_DB
    databaseName: orimeguri_db
    user: Orimeguri
    region: singapore

services:
  - type: web
    name: Orimeguri
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Orimeguri_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false